site_name: UP SITAW Docs
site_url: https://up-sitaw.github.io/
nav:
  - Home: index.md
  - 'Developer Documentation':
    - 'Lifeline Web App': developer/lifeline-web-app/index.md
    - 'Lifeline Deployment':
      - 'Deploying Lifeline on Docker': developer/lifeline-deployment/deploying-lifeline-on-docker.md
      - 'Post Installation': developer/lifeline-deployment/post-installation.md
    - myBESHIE:
      - 'Setting up ROS Simulator for Lifeline Navigation Development': developer/myBESHIE/setting-up-ros-simulator.md
      - 'Installing dependencies required by Lifeline': developer/myBESHIE/installing-lifeline-dependencies.md
      - 'Running required services by Lifeline': developer/myBESHIE/running-required-services-by-lifeline.md
      - 'Creating a Desktop Shortcut on myBESHIE for Lifeline Jitsi Meetings': developer/myBESHIE/creating-desktop-shortcut.md
  # - About: about.md
  # - Getting Started:
  #   - Installation: installation.md
  #   - Configuration: configuration.md
  #   - Deployment: deployment.md
  # - Usage:
  #   - Basic Usage: usage.md
  #   - Advanced Usage: advanced.md
  # - Contributing: contributing.md
  # - Changelog: changelog.md
  # - License: license.md
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode